services:
  db:
    image: redis:alpine
    container_name: redis-db
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  server:
    image: abhi0874/codelave-server:v2
    container_name: codelave-server
    user: "root"
    ports:
      - "3000:3000"
    env_file:
      - ./server/.env
    volumes:
      # This socket is the magic that allows your backend container 
      # to spawn new sandbox containers on your host machine!
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - db

  client:
    image: abhi0874/codelave-client:v2
    container_name: codelave-client
    ports:
      - "3001:3001"
    depends_on:
      - server

volumes:
  redis_data: