apiVersion: v1
kind: Service
metadata:
  name: codelave-server-svc
  labels:
    app: codelave-server

spec:
  type: ClusterIP
  selector:
    app: codelave-server
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP